<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="15.1.3" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="9.0.12" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="9.0.12" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\WalletWise.Domain\WalletWise.Domain.csproj" />
  </ItemGroup>

</Project>
