<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\WalletWise.Application\WalletWise.Application.csproj" />
    <ProjectReference Include="..\WalletWise.Domain\WalletWise.Domain.csproj" />
  </ItemGroup>

</Project>
